type User @table {
  username: String!
  email: String!
  role: String!
  createdAt: Timestamp!
  displayName: String
  phoneNumber: String
}

type Customer @table {
  name: String!
  email: String!
  createdAt: Timestamp!
  phoneNumber: String
  address: String
}

type Enquiry @table {
  customer: Customer!
  subject: String!
  description: String!
  status: String!
  createdAt: Timestamp!
  assignedToUser: User
  priority: String
  resolutionDate: Timestamp
}

type EnquiryUpdate @table {
  enquiry: Enquiry!
  user: User!
  updateText: String!
  createdAt: Timestamp!
  newStatus: String
}